### PR TITLE
Remove agentkeepalive from terafoundation

### PR DESCRIPTION
**Pull request by godber**
This commit removes the agentkeepalive wrapper and dependency
from terafoundation.

refs #84

### CODE REVIEW

**Comment by godber** [comment]
This is effectively a work in progress since it hasn't been tested in any way.  How do you guys test things in terafoundation?  I guess I could `npm link` it into teraslice.  I'll try that tomorrow.

**Comment by kstaken** [comment]
Yes npm link

**Comment by kstaken** [comment]
Is this ready for merging?

**Comment by godber** [comment]
Sure, looks like teraslice still works running this job, and we get the right doc count:

```json
{
    "name": "Gen 1m docs",
    "lifecycle": "once",
    "workers": 20,
    "operations": [
        {
            "_op": "elasticsearch_reader",
            "index": "one-million-1",
            "type": "event",
            "size": 5000,
            "date_field_name": "created"
        },
        {
            "_op": "elasticsearch_index_selector",
            "index": "one-million-2-no-dupe",
            "type": "events"
        },
        {
            "_op": "elasticsearch_bulk",
            "size": 5000
        }
    ]
}
```

**Pull request merged**
